//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInventory
    {
        public int AccountID { get; set; }
        public string AccountName { get; set; }
        public int LocationID { get; set; }
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<long> Quantity { get; set; }
    }
}
