//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBalance
    {
        public int ID { get; set; }
        public int AccountID { get; set; }
        public int AccountKey { get; set; }
        public decimal Balance { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
