//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AccountBalances = new HashSet<AccountBalance>();
            this.Assets = new HashSet<Asset>();
            this.Characters = new HashSet<Character>();
            this.Corporations = new HashSet<Corporation>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int ApiKeyID { get; set; }
        public string ApiVerificationCode { get; set; }
        public int ApiKeyType { get; set; }
        public int ApiAccessMask { get; set; }
        public bool DeletedFlag { get; set; }
    
        public virtual ICollection<AccountBalance> AccountBalances { get; set; }
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
        public virtual ICollection<Corporation> Corporations { get; set; }
    }
}
