//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public Asset()
        {
            this.BlueprintInstances = new HashSet<BlueprintInstance>();
        }
    
        public long ID { get; set; }
        public int ItemID { get; set; }
        public int Quantity { get; set; }
        public int AccountID { get; set; }
        public int LocationID { get; set; }
        public Nullable<int> ContainerID { get; set; }
        public bool DeletedFlag { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Item Item { get; set; }
        public virtual ICollection<BlueprintInstance> BlueprintInstances { get; set; }
    }
}
