//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPMEntities : DbContext
    {
        public EPMEntities()
            : base("name=EPMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<AccountBalance> AccountBalances { get; set; }
        public DbSet<Asset> Assets { get; set; }
        public DbSet<Blueprint> Blueprints { get; set; }
        public DbSet<BlueprintInstance> BlueprintInstances { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Character> Characters { get; set; }
        public DbSet<Configuration> Configurations { get; set; }
        public DbSet<Container> Containers { get; set; }
        public DbSet<Corporation> Corporations { get; set; }
        public DbSet<EveApiStatu> EveApiStatus { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<invBlueprintType> invBlueprintTypes { get; set; }
        public DbSet<invCategory> invCategories { get; set; }
        public DbSet<invGroup> invGroups { get; set; }
        public DbSet<invTypeMaterial> invTypeMaterials { get; set; }
        public DbSet<invType> invTypes { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<Manifest> Manifests { get; set; }
        public DbSet<MarketImport> MarketImports { get; set; }
        public DbSet<MarketOrder> MarketOrders { get; set; }
        public DbSet<ProductionJob> ProductionJobs { get; set; }
        public DbSet<ramTypeRequirement> ramTypeRequirements { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<SolarSystem> SolarSystems { get; set; }
        public DbSet<Station> Stations { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<AccountInventory> AccountInventories { get; set; }
        public DbSet<ActiveCharacter> ActiveCharacters { get; set; }
        public DbSet<ActiveCorporation> ActiveCorporations { get; set; }
        public DbSet<ActiveMarketOrder> ActiveMarketOrders { get; set; }
        public DbSet<BuildableItem> BuildableItems { get; set; }
        public DbSet<InboundContract> InboundContracts { get; set; }
        public DbSet<ItemCategory> ItemCategories { get; set; }
        public DbSet<ItemCost> ItemCosts { get; set; }
        public DbSet<ItemCostVariance> ItemCostVariances { get; set; }
        public DbSet<ItemDailySale> ItemDailySales { get; set; }
        public DbSet<ItemOrder> ItemOrders { get; set; }
        public DbSet<ItemPrice> ItemPrices { get; set; }
        public DbSet<ItemProducing> ItemProducings { get; set; }
        public DbSet<ItemPurchase> ItemPurchases { get; set; }
        public DbSet<ItemSale> ItemSales { get; set; }
        public DbSet<ItemSaleRolling7> ItemSaleRolling7 { get; set; }
        public DbSet<ItemTransaction> ItemTransactions { get; set; }
        public DbSet<MarketCurrentCost> MarketCurrentCosts { get; set; }
        public DbSet<MarketCurrentPrice> MarketCurrentPrices { get; set; }
        public DbSet<MarketCurrentRangeCost> MarketCurrentRangeCosts { get; set; }
        public DbSet<MarketRangeCost> MarketRangeCosts { get; set; }
        public DbSet<MarketReprice> MarketReprices { get; set; }
        public DbSet<MarketRestock> MarketRestocks { get; set; }
        public DbSet<MaterialCost> MaterialCosts { get; set; }
        public DbSet<MaterialCostVariance> MaterialCostVariances { get; set; }
        public DbSet<MaterialItem> MaterialItems { get; set; }
        public DbSet<MaterialRequirement> MaterialRequirements { get; set; }
        public DbSet<OutboundContract> OutboundContracts { get; set; }
        public DbSet<ProductionBlueprint> ProductionBlueprints { get; set; }
        public DbSet<ProductionMaterialAvailable> ProductionMaterialAvailables { get; set; }
        public DbSet<ProductionQueue> ProductionQueues { get; set; }
        public DbSet<ProductionQueueMaterial> ProductionQueueMaterials { get; set; }
        public DbSet<PurchaseRelist> PurchaseRelists { get; set; }
        public DbSet<PurchaseReprice> PurchaseReprices { get; set; }
        public DbSet<RegionInventory> RegionInventories { get; set; }
        public DbSet<RegularAsset> RegularAssets { get; set; }
    }
}
