//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketRestock
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public int Quantity { get; set; }
        public int LocationID { get; set; }
        public Nullable<decimal> MarketPrice { get; set; }
        public Nullable<decimal> UndercutPrice { get; set; }
        public Nullable<decimal> ItemCost { get; set; }
        public Nullable<decimal> Variance { get; set; }
    }
}
