//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutboundContract
    {
        public string ItemName { get; set; }
        public Nullable<long> AmarrQuantity { get; set; }
        public Nullable<long> PenirQuantity { get; set; }
        public string AccountName { get; set; }
    }
}
