//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionJob
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public int Quantity { get; set; }
        public int Status { get; set; }
        public System.DateTime WhenInstalled { get; set; }
        public Nullable<System.DateTime> WhenStarted { get; set; }
        public Nullable<System.DateTime> WhenCompleted { get; set; }
        public Nullable<System.DateTime> WhenPaused { get; set; }
        public Nullable<int> AssetID { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
