//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRelist
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> PurchaseQuantity { get; set; }
        public Nullable<long> InventoryQuantity { get; set; }
        public Nullable<long> RequiredQuantity { get; set; }
        public decimal AmarrPrice { get; set; }
        public decimal CurrentPrice { get; set; }
        public Nullable<decimal> RangePrice { get; set; }
        public Nullable<long> PctOfRequired { get; set; }
        public int ProductionQuantityNeeded { get; set; }
        public long ProductionQuantityAvailable { get; set; }
    }
}
