//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long ID { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Quantity { get; set; }
        public int ItemID { get; set; }
        public decimal Price { get; set; }
        public TransactionType TransactionType { get; set; }
        public int CharacterID { get; set; }
        public int CorporationID { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Corporation Corporation { get; set; }
        public virtual Item Item { get; set; }
    }
}
